### ISSUE TITLE
Update 4.3.1: All step tiles in step widgets are gone in all dashbaords

### ISSUE THREAD

**Issue by iSimsi** [xresch/EngineeredMonitoringPlatform#7]
After update to Version 4.3.1 All step tiles in step widgets are gone in all dashbaords. After resaving a widget the tile is visbile, but disapears again after some seconds.

The UI  show's the follwing errors:
Unexpected Error Occured: Cannot invoke "com.xresch.cfw.utils.CFWHttp$CFWHttpResponse.getStatus()" because "response" is null
Exception occured: Connection xxx.xxx.xxx.xxx:xxxxx<->xx.xxx.xx.xxx:xx is still allocated

**Comment by iSimsi** [comment]
Also Dynatrace widgets have started failing since the restart after update, we had to roleback

**Comment by xresch** [comment]
Ciao @iSimsi,

issue was introduced with the changes that were made towards supporting accessing your Mimir instance with client certificates.
Issue should be fixed with the following commit.
https://github.com/xresch/CoreFramework/commit/4963a4fce31d6d452a6f89814f8ed242dc0bab6b

I will upload a new patch version to your minio.

**Comment by iSimsi** [comment]
Thanks for fixing

**Comment by xresch** [comment]
you are welcome
